# Generated by Django 4.2.2 on 2023-06-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review_facility_lat_facility_lon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
