# Generated by Django 4.2.2 on 2023-06-22 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_facility_latitude_facility_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='longitude',
            new_name='lon',
        ),
    ]
