# Generated by Django 4.2.2 on 2023-06-27 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_facility_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stars', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
