# Generated by Django 4.2.2 on 2023-06-24 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_latitude_facility_lat_and_more'),
    ]

    operations = [
    ]
