# Generated by Django 4.2.2 on 2023-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reviews',
            field=models.ManyToManyField(to='api.review'),
        ),
    ]
