# Generated by Django 4.2.2 on 2023-06-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_facility_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='reviews',
            field=models.ManyToManyField(null=True, to='api.review'),
        ),
    ]
