# Generated by Django 4.2.2 on 2023-06-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_facility_lat_alter_facility_lon_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
