# Generated by Django 4.2.2 on 2023-06-26 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_review_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
