# Generated by Django 4.2.2 on 2023-06-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
