# Generated by Django 4.2.2 on 2023-06-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_review_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
        migrations.AddField(
            model_name='facility',
            name='facility_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
