# Generated by Django 4.2.2 on 2023-06-30 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_facility_facility_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='facility_id',
            new_name='id',
        ),
    ]
