# Generated by Django 4.2.2 on 2023-06-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
