# Generated by Django 4.2.2 on 2023-06-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_review_email_alter_review_stars_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
