# Generated by Django 4.2.2 on 2023-07-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_facility_id_facility_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='emailAddress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
