# Generated by Django 4.2.2 on 2023-07-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_facility_emailaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='emailAddress',
            new_name='email_address',
        ),
    ]
