# Generated by Django 4.2.2 on 2023-07-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_emailaddress_facility_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='email_address',
            field=models.CharField(max_length=100),
        ),
    ]
