# Generated by Django 4.2.2 on 2023-07-16 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_facility_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
    ]
