# Generated by Django 4.2.2 on 2023-07-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_facility_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
