# Generated by Django 4.2.2 on 2023-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_facility_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
