# Generated by Django 4.2.2 on 2023-06-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_review_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='facility',
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
