# Generated by Django 4.2.2 on 2023-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_facility_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='lon',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20),
        ),
    ]
