# Generated by Django 4.2.2 on 2023-06-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='facility',
        ),
    ]
