# Generated by Django 4.2.2 on 2023-06-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_review_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facility'),
        ),
    ]
