# Generated by Django 4.2.2 on 2023-07-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(models.F('facility'), models.F('user'), name='first_last_name_unique'),
        ),
    ]
