# Generated by Django 4.2.2 on 2023-07-26 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_review_first_last_name_unique_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='first_last_name_unique',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('facility', 'user')},
        ),
    ]
