# Generated by Django 4.2.2 on 2023-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_review_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reviews',
            field=models.ManyToManyField(to='api.review'),
        ),
    ]
