# Generated by Django 4.2.2 on 2023-06-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_facility_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='reviews',
        ),
        migrations.AddField(
            model_name='facility',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.review'),
        ),
    ]
