# Generated by Django 4.2.2 on 2023-06-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_facility_reviews_facility_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='reviews',
        ),
    ]
