# Generated by Django 4.2.2 on 2023-06-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_facility_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='reviews',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.facility'),
        ),
    ]
